name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            InterviewPro/package-lock.json
            InterviewPro/functions/package-lock.json
      - name: Install dependencies (web app)
        working-directory: InterviewPro
        run: npm ci
      - name: Run ESLint (web app)
        working-directory: InterviewPro
        run: npm run lint
      - name: Install dependencies (functions)
        working-directory: InterviewPro/functions
        run: npm ci
      - name: Run ESLint (functions)
        working-directory: InterviewPro/functions
        run: npm run lint
